name: Test
on:
  pull_request:
  push:
jobs:
  emacs_test:
    name: Test Emacs configs
    runs-on: macos-latest
    steps:
      - name: Install Emacs
        run: brew --cask install emacs
      - name: Clone project
        uses: actions/checkout@v2
      - name: Run Emacs
        run: emacs --batch --script .emacs.el
